CREATE DATABASE gymbookingsyste;
USE gymbookingsyste;
DROP TABLE Clients;
DROP TABLE Trainers;
DROP TABLE Bookings;

CREATE TABLE Clients (
    CLIENT_ID INT AUTO_INCREMENT,
    FNAME VARCHAR(30),
    LNAME VARCHAR(30),
    GENDER VARCHAR(30),
    AGE VARCHAR(2),
    PRIMARY KEY(CLIENT_ID)
);

CREATE TABLE Trainers (
     TRAINER_ID INT AUTO_INCREMENT,
     FNAME VARCHAR(30),
     LNAME VARCHAR(30),
     GENDER VARCHAR(30)
     PRIMARY KEY(TRAINER_ID)
);


CREATE TABLE Bookings (
    BOOKING_ID INT AUTO_INCREMENT,
    CLIENT_ID INT NOT NULL,
    TRAINER_ID INT NOT NULL,
    BOOKING_DATE DATE NOT NULL,
    BOOKING_TIME INT NOT NULL,
    DURATION_OF_SESSION INT NOT NULL;
    FOCUS VARCHAR(30),
    PRIMARY KEY(BOOKING_ID),
    FOREIGN KEY(CLIENT_ID) REFERENCES Clients(CLIENT_ID),
    FOREIGN KEY(TRAINER_ID) REFERENCES Trainers(TRAINER_ID)
);

INSERT INTO Clients (FNAME, LNAME, GENDER, AGE)
VALUES("John", "Smith", "MALE", "18"), ("Leonardo", "Simpson", "MALE", "28");

INSERT INTO Trainers(FNAME, LNAME, GENDER)
VALUES("LEO", "SMITH", "MALE");

INSERT INTO Bookings(BOOKING_ID, CLIENT_ID, TRAINER_ID, BOOKING_DATE, BOOKING_TIME, DURATION_OF_SESSION)
VALUES(1, 1,1,"2020-01-10", "0300", "20");

SELECT * FROM Clients;
SELECT * FROM Trainers;
SELECT * from Bookings;
